### ISSUE TITLE
Setting allowedExtensions from within my controller

### ISSUE THREAD

**Issue by kenwinans** [srs81/CakePHP-AjaxMultiUpload#43]
First, let me thank you for your fine plugin.

Second, I'm new to GitHub so maybe this is not the proper place for this, but...

I would like to be able to modify the list of allowedExtensions from within the controller that I have attached the AMU component to.

I have a working installation but in my Tracks controller I want to restrict the file types to ".mp3" files and in the Images controller I want only ".jpg" or ".png" files.

In my Tracks controller I have tried to accomplish this by putting the following line in my beforeFilter() function as follows:
$this->Upload->allowedExtensions = array('mp3');

It has no effect.

Conversely, when I edit the AMU UploadsController.php file like this:
protected allowedUploads = array('mp3');
I get the expected result - i.e. when trying to upload a file other than mp3, an error is issued.

Should there be a setAllowedExtensions() method in UploadCompnent? 

Any suggestions? 

Thanks,
Ken

**Comment by srs81** [comment]
I've added the feature to let you set allowed file types to upload in the controller, as a parameter in this->Upload->edit() . Can you check if it works fine now?
