### ISSUE TITLE
Upload button not showing

### ISSUE THREAD

**Issue by vanevane** [srs81/CakePHP-AjaxMultiUpload#44]
I'm using cake 2.4 and before i added auth and acl components the buttons was showing just right, but after that it doesn't show anymore.
I tried putting "$this->Auth->allow();" ;just to make the button; into the plugin controllers since it worked with anoter plugin, but no...it doesn't work. Is there a way to solve this?

**Comment by srs81** [comment]
This should be fixed with the latest updates - the uploader now uses Dropzone.js rather than the older one, please check if its OK now.
