### ISSUE TITLE
Only "Files" word

### ISSUE THREAD

**Issue by Andres-Chandia** [srs81/CakePHP-AjaxMultiUpload#46]
Hi there, I have followed three times your instructions to implement the plugin but the result is always the same, I only get the word "Files" at the place of the form, I'm puting it at the index view: View/Terms/index.ctp, but I tried at the view.ctp file also and it happens the same.
Just in case:
cakephp/app/Plugin/AjaxMultiUpload#  ls
Config  Console  Controller  Lib  LICENSE  Model  README.md  Test  Vendor  View  webroot
Add to bootstrap.php load => done
Create file directory => done
Add to controller => done
Add to views => View/Terms/index.ctp => ``` <?php echo $this->Upload->view('Term', $term['Term']['id']); ?> ``` 

thanks for your help

**Comment by srs81** [comment]
This should be fixed with the latest updates - the uploader now uses Dropzone.js rather than the older one, please check if its OK now.
