### ISSUE TITLE
When using cake 2.5 with Auth Component

### ISSUE THREAD

**Issue by notoriousturtle** [srs81/CakePHP-AjaxMultiUpload#47]
Hi, 

The solution you provided in the Gotchas section doesn't work for the latest Cake 2.5. Users need to edit UploadsController.php and add the following instead:
        public function beforeFilter() {
                parent::beforeFilter();

                //need to disable Security component
                $this->Security->unlockedActions = array('upload');
        }

Cheers.

**Comment by srs81** [comment]
Thanks! I've updated the documentation to mention this and credited your GitHub handle as well.
