### ISSUE TITLE
Problems with the upload.php save function

### ISSUE THREAD

**Issue by jgsacris** [srs81/CakePHP-AjaxMultiUpload#48]
I have been having problems with the save function on the upload.php file. For some reason fopen("php://input", "r"); was returning zero bites.

I was able to solve the issue replacing the whole function with:
```
function save($path) {
        file_put_contents($path, file_get_contents("php://input"));        
        return true;
}
```
I hope this helps!

**Comment by srs81** [comment]
This should be fixed with the latest updates - the uploader now uses Dropzone.js rather than the older one, please check if its OK now.
