### ISSUE TITLE
Notice (8): Undefined variable: str [APP\Plugin\AjaxMultiUpload\View\Helper\UploadHelper.php, line 49]]

### ISSUE THREAD

**Issue by maungyehtunzaw** [srs81/CakePHP-AjaxMultiUpload#51]
i got this error with integrate cakephp version 2.3.8 ..

**Comment by nandosb** [comment]
@maungyehtunzaw  It ´s no related with your CakePHP version. It´s a development bug. This plugin was working fine until version 1.0.3.

Anyway, can someone else fix this this problem? Dropzone integration it´s not working.

Thanks

**Comment by srs81** [comment]
Sorry, this should be fixed now - can you check with the latest version please?

**Comment by srs81** [comment]
@nandosb - is your problem fixed now? Or is Dropzone not working?

**Comment by nandosb** [comment]
I´m affraid it still has a problem. 

Check UploadHelper.php, around the line 78. I think you should change 

Dropzone.options = {
                    maxFilesize = $size
		        }

for

Dropzone.options = {
                    maxFilesize : $size
		        }

and move the script bellow the <form> tag.

**Comment by nandosb** [comment]
@srs81  Please, check multi uploads too. When I tried to setup two upload fields, I got the following js error "Uncaught Error: Dropzone already attached."

Thanks

**Comment by srs81** [comment]
Thanks for testing - just made those changes. Can you check again?

Let me check on the "Dropzone already attached" error.

**Comment by srs81** [comment]
I believe this should be fixed now. Can you create a new issue for the "Dropzone already attached" error?
